#!/usr/bin/env python

# Runs a loop that varies the pool size of the site

import subprocess


def run(nt):
    cmd = f"cat site-template.yaml | sed 's/max_threads:.*/max_threads: {nt}/' > site.yaml" 
    subprocess.run(cmd, shell=True, check=True)
    subprocess.run("./run-one | tee out-site.txt", shell=True, check=True)
    subprocess.run(f"{{ cat out-site.txt | grep Stats | tr -d '\\n'; echo ', np={nt}'; }} 2>&1 >>loop-site-results.txt", shell=True, check=True)


NT = [4, 8, 16, 32, 64]

for nt in NT:
    run(nt)


